### ISSUE TITLE
Resize editor when containing div changes size

### ISSUE THREAD

**Issue by vadgaard** [ulrikrasmussen/BoxProver#3]
Currently, the text area of the Ace editor does not resize when the containing div resizes (by moving the `hsplitter` or `vsplitter` ellements).

This should be easily fixed by adding

    aceEditor.resize()

to the last line line of the function `updateLayout()` in `frontend/frontend.js`.

**Comment by ulrikrasmussen** [comment]
Thanks for the report and for the fix! Fixed in https://github.com/ulrikrasmussen/BoxProver/commit/a22e82ad535b8ffe105e317dbca1b99cc6c9f027
